from items import *

item_synthesis_path = {}
unique_item_synthesis_path = {}
#shoes
unique_item_synthesis_path["Berserker's Greaves"] = ('Boots', 'Dagger')
unique_item_synthesis_path['Plated Steelcaps'] = ('Boots', 'Cloth Armor')
item_synthesis_path['Ionian Boots of Lucidity'] = ('Boots', 600)
item_synthesis_path["Sorcerer's Shoes"] = ('Boots', 600)
item_synthesis_path["Mercury's Treads"] = ('Boots', 'Magic Mantle')

#epic items
epic_item_synthesis_path = {}
epic_item_synthesis_path['Serrated Dirk'] = ('Long Sword', 'Long Sword')
epic_item_synthesis_path['Warhammer'] = ('Long Sword', 'Long Sword')
epic_item_synthesis_path['Hexdrinker'] = ('Long Sword', 'Magic Mantle')
epic_item_synthesis_path['Kindlegem'] = ('Ruby Crystal', 'Ruby Crystal')
epic_item_synthesis_path['Vampiric Scepter'] = ('Long Sword', 'Long Sword')
epic_item_synthesis_path['Fiendish Codex'] = ('Amplifying Tome', 'Amplifying Tome')
epic_item_synthesis_path['Leeching Leer'] = ('Amplifying Tome', 'Ruby Crystal')
epic_item_synthesis_path['Needlessly Large Rod'] = ('Amplifying Tome', 'Amplifying Tome')
epic_item_synthesis_path['Last Whisper'] = ('Long Sword', 'Agility Cloak')
epic_item_synthesis_path['Zeal'] = ('Dagger', 'Agility Cloak')
epic_item_synthesis_path['B.F.Sword'] = ('Long Sword', 'Long Sword')
epic_item_synthesis_path['Chain Vest'] = ('Cloth Armor', 'Ruby Crystal')
epic_item_synthesis_path["Giant's Belt"] = ('Ruby Crystal', 'Ruby Crystal')
epic_item_synthesis_path['Glacial Buckler'] = ('Cloth Armor', 'Sapphire Crystal')
epic_item_synthesis_path['Negatron Cloak'] = ('Magic Mantle', 'Magic Mantle')
epic_item_synthesis_path['Aegis of the Legion'] = ('Magic Mantle', 'Cloth Armor')
epic_item_synthesis_path['Blighting Jewel'] = ('Amplifying Tome', 'Amplifying Tome')

epic_unique_item_synthesis_path = {}
epic_unique_item_synthesis_path['Lost Chapter'] = ('Amplifying Tome', 'Sapphire Crystal', 600)
epic_unique_item_synthesis_path['Phage'] = ['Long Sword', 'Ruby Crystal', 600]
epic_unique_item_synthesis_path['Tiamat'] = ('Long Sword', 'Long Sword', 600)
epic_unique_item_synthesis_path['Sheen'] = (600)
epic_unique_item_synthesis_path['Hextexh Alternator'] = ('Amplifying Tome', 'Ruby Crystal', 600)
epic_unique_item_synthesis_path['Catalyst of Aeons'] = ('Catalyst of Aeons', 'Sapphire Crystal', 600)
epic_unique_item_synthesis_path['Hearthbound Axe'] = ('Long Sword', 'Dagger', 600)
epic_unique_item_synthesis_path['Kircheis Shard'] = ('Long Sword', 'Dagger', 600)
epic_unique_item_synthesis_path['Noonquiver'] = ('Long Sword', 'Dagger', 600)
epic_unique_item_synthesis_path['Rageknife'] = ('Dagger', 'Amplifying Tome', 600)
epic_unique_item_synthesis_path['Recurve Bow'] = ('Dagger', 'Dagger', 600)
epic_unique_item_synthesis_path["Bami's Cinder"] = ('Ruby Crystal', 'Ruby Crystal', 600)
epic_unique_item_synthesis_path['Bramble Vest'] = ('Cloth Armor', 'Cloth Armor', 600)
epic_unique_item_synthesis_path["Spectre's Cowl"] = ('Magic Mantle', 'health', 600)
epic_unique_item_synthesis_path["Warden's Mail"] = ('Cloth Armor', 'Cloth Armor', 600)
epic_unique_item_synthesis_path['Winged Moonplate'] = ('Ruby Crystal', 'Ruby Crystal', 600)

#legendary items
legendary_items_synthesis_path = {}
legendary_items_synthesis_path['Cosmic Drive'] = ('Kindlegem', 'Fiendish Codex')
legendary_items_synthesis_path['Void Staff'] = ('Blighting Jewel', 'Fiendish Codex')

legendary_unique_items_synthesis_path = {}
legendary_unique_items_synthesis_path['Maw of Malmortius'] = ('Warhammer', 'Hexdrinker', 600)
legendary_unique_items_synthesis_path['Titanic Hydra'] = ('Kindlegem', 'Tiamat', 600)
legendary_unique_items_synthesis_path['Ravenous Hydra'] = ('Tiamat', 'Warhammer', 600)
legendary_unique_items_synthesis_path["Death's Dance"] = ('Warhammer', 'Kindlegem', 600)
legendary_unique_items_synthesis_path['Spear of Shojin'] = ('Warhammer', 'Kindlegem', 600)
legendary_unique_items_synthesis_path['Divine Sunderer'] = ('Phage', 'Sheen', 600)
legendary_unique_items_synthesis_path['Demonic Embrace'] = ('Fiendish Codex', "Giant's Belt", 600)
legendary_unique_items_synthesis_path['Horizon Focus'] = ('Fiendish Codex', 'Hextexh Alternator', 600)
legendary_unique_items_synthesis_path['Lich Bane'] = ('Sheen', 'Fiendish Codex', 600)
legendary_unique_items_synthesis_path["Rabadon's Deathcap"] = ('Needlessly Large Rod', 'Needlessly Large Rod', 600)
legendary_unique_items_synthesis_path["Rylai's Crystal Scepter"] = ('Fiendish Codex', 'Catalyst of Aeons', 600)
legendary_unique_items_synthesis_path['Rod of Ages'] = ('Lost Chapter', 'Catalyst of Aeons', 600)
legendary_unique_items_synthesis_path['Hextech Gunblade'] = ('Hextexh Alternator', 'Vampiric Scepter', 600)
legendary_unique_items_synthesis_path["Luden's Tempest"] = ('Lost Chapter', 'Blighting Jewel', 600)
legendary_unique_items_synthesis_path["Liandry's Anguish"] = ('Lost Chapter', 'Fiendish Codex', 600)
legendary_unique_items_synthesis_path['Bloodthirster'] = ('Vampiric Scepter', 'B.F.Sword', 600)
legendary_unique_items_synthesis_path['kraken Slayer'] = ('Noonquiver', 'Last Whisper', 600)
legendary_unique_items_synthesis_path["Lord Dominik's Regards"] = ('Last Whisper', 'Recurve Bow', 600)
legendary_unique_items_synthesis_path["Nashor's Tooth"] = ('Recurve Bow', 'Fiendish Codex', 600)
legendary_unique_items_synthesis_path["Rapid Firecannon"] = ('Zeal', 'Kircheis Shard', 600)
legendary_unique_items_synthesis_path["Runaan's Hurricane"] = ('Recurve Bow', 'Zeal', 600)
legendary_unique_items_synthesis_path['Statikk Shiv'] = ('Zeal', 'Kircheis Shard', 600)
legendary_unique_items_synthesis_path["Wit's End"] = ('Negatron Cloak', 'Recurve Bow', 600)
legendary_unique_items_synthesis_path['Navori Quickblades'] = ('Warhammer', 'Zeal', 600) 
legendary_unique_items_synthesis_path["Guinsoo's Rageblade"] = ('Noonquiver', 'Rageknife', 600)
legendary_unique_items_synthesis_path['Abyssal Mask'] = ('Kindlegem', 'Negatron Cloak', 600)
legendary_unique_items_synthesis_path["Dead Man's Plate"] = ('Chain Vest', 'Winged Moonplate', 600)
legendary_unique_items_synthesis_path['Force of Nature'] = ('Negatron Cloak', 'Negatron Cloak', 600)
legendary_unique_items_synthesis_path["Randuin's Omen"] = ("Giant's Belt", "Warden's Mail", 600)
legendary_unique_items_synthesis_path['Spirit Visage'] = ('Kindlegem', "Spectre's Cowl", 600)
legendary_unique_items_synthesis_path["Sterak's Gage"] = ("Giant's Belt", "Giant's Belt", 600)
legendary_unique_items_synthesis_path['Thornmail'] = ("Giant's Belt", 'Bramble Vest', 600)
legendary_unique_items_synthesis_path["Warmog's Armor"] = ("Giant's Belt", "Giant's Belt", 600)
legendary_unique_items_synthesis_path['Frostfire Gauntlet'] = ('Sheen', "Bami's Cinder", 600)
legendary_unique_items_synthesis_path["Jak'sSho, The Protean"] = ('Vampiric Scepter', 'Aegis of the Legion', 600)
legendary_unique_items_synthesis_path['Heartsteel'] = ('Sheen', "Giant's Belt", 600)
